# Generated by Django 3.2.7 on 2021-09-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=2000)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
