# Generated by Django 3.2.7 on 2021-09-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
