# Generated by Django 3.2.7 on 2021-09-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='join_code',
            field=models.CharField(blank=True, default='FA7D3', max_length=5, unique=True),
        ),
    ]
