# Generated by Django 3.2.7 on 2021-09-24 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='events',
            field=models.CharField(default=django.utils.timezone.now, max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='join_code',
            field=models.CharField(blank=True, default='BB32B', max_length=5, unique=True),
        ),
    ]
