# Generated by Django 3.2.7 on 2021-09-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20210924_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='join_code',
            field=models.CharField(blank=True, default='18C32', max_length=5, unique=True),
        ),
    ]
