# Generated by Django 3.2.7 on 2021-09-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='budget',
            field=models.IntegerField(default=1),
        ),
    ]
