# Generated by Django 3.2.7 on 2021-09-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_id',
        ),
    ]
